//
// This file was generated by the Retargetable Decompiler
// Website: http://decompiler.fit.vutbr.cz
// Copyright (c) 2011-2014 Lissom <decompiler@fit.vutbr.cz>
//

#include <fcntl.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

/* -------- Function Prototypes --------- */

int32_t init(void);
int32_t read_80_bytes(int8_t * buf);

/* ------------- Functions -------------- */

int32_t init(void) {
    int32_t fd = open("/home/rsbo/flag", O_RDONLY); // 0x80485a2
    int8_t * buf;
    read(fd, buf, 16);
    int32_t v1 = 0x1000000 * (int32_t)buf / 0x1000000; // 0x80485f0
    int32_t time_val = time(NULL); // 0x804864f12
    // branch -> 0x80485dc
    int32_t seed; // 0x8048607
    for (uint32_t i = 0; i < 16; i++) {
        // 0x80485dc
        seed = (1337 * time_val + v1) % 0x7fffffff;
        // PHI copies at the loop end
        time_val = seed;
        // loop 0x80485dc end
    }
    // 0x8048629
    close(fd);
    memset((int32_t *)buf, 0, 16);
    srand(seed);
    return seed;
}

int32_t read_80_bytes(int8_t * buf) {
    // 0x804865c
    return read(0, buf, 128);
}

int main(int argc, char **argv) {
    // bb
    alarm(30);
    init();
    int8_t * buf;
    int32_t nbyte = read_80_bytes(buf); // 0x80486a0
    if (nbyte <= 0) {
        // 0x8048712
        write(1, buf, nbyte);
        return 0;
    }
    rand();
    int32_t v1 = 1; // 0x80486bc
    int8_t * buf2 = (int8_t *)((int32_t)buf % 256); // bp+14
    while (v1 != nbyte) {
        // 0x80486b3
        rand();
        v1++;
        buf2 = (int8_t *)((int32_t)buf2 % 256);
        // continue -> 0x80486b3
    }
    // 0x8048712
    write(1, buf2, nbyte);
    return 0;
}

/* --------- External Functions --------- */

// unsigned alarm(unsigned)
// int close(int)
// void * memset (void *, int, size_t)
// int open(const char *path, int oflag, ... )
// int rand ()
// ssize_t read(int fildes, void *buf, size_t nbyte)
// void srand (unsigned int)
// time_t time(time_t *tloc)
// ssize_t write(int fildes, const void *buf, size_t nbyte)

/* ---------- Meta-Information ---------- */

// Detected compiler: llvm (i686-pc-linux-gnu) 3.2
// Detected functions: 3 (3 in front-end)
// Decompiler release: v1.7 (Jun 30 2014)
// Decompilation date: Aug 16 2014 07:38:08
