//
// This file was generated by the Retargetable Decompiler
// Website: http://decompiler.fit.vutbr.cz
// Copyright (c) 2011-2014 Lissom <decompiler@fit.vutbr.cz>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <time.h>
#include <unistd.h>

/* ------------- Structures ------------- */

struct tm {
    int32_t e0;
    int32_t e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    int32_t e5;
    int32_t e6;
    int32_t e7;
    int32_t e8;
};

/* -------- Function Prototypes --------- */

int32_t function_8048490(int32_t a1);
int32_t function_804855d(int32_t a1, int8_t * format);
int32_t function_80485ce(int32_t a1);
int32_t function_80486b1(void);
int32_t function_80487b0(int8_t * a1, int32_t a2);
int32_t function_80487e4(int8_t * a1, int32_t a2, int32_t a3);
// The following external functions do not have any associated header file:
void __stack_chk_fail(void);
void __gmon_start__(void);

/* ---------- Global Variables ---------- */

int32_t g1 = 0; // 0x804a044
int32_t g2 = 0; // gpr0
bool g3 = false; // zf0

/* ------------- Functions -------------- */

int32_t function_8048490(int32_t a1) {
    // 0x8048490
    return g2;
}

int32_t function_804855d(int32_t a1, int8_t * format) {
    int32_t result = (int32_t)format; // 0x804856f
    g3 = true;
    g2 = result;
    int8_t * str;
    sprintf(str, format);
    function_80487e4(str, result, a1);
    if (!g3) {
        // 0x80485c7
        __stack_chk_fail();
        // branch -> 0x80485cc
    }
    // 0x80485cc
    return result;
}

int32_t function_80485ce(int32_t a1) {
    int8_t v1[4]; // bp-112
    int8_t v2[4]; // bp-128
    // 0x80485ce
    int32_t result = g2; // 0x80485dd
    v2[0] = 32;
    v2[4] = 32;
    v2[8] = 32;
    v2[12] = 115;
    v1[0] = 37;
    v1[4] = 10;
    v1[8] = 0;
    v1[12] = 0;
    int32_t * t;
    time(t);
    int32_t time_info = (int32_t)localtime(t); // bp-144
    int32_t v3;
    strftime((int8_t *)&v3, 80, "%H:%M:%S ", (struct tm *)&time_info);
    int32_t v4 = (int32_t)t; // bp+24
    int32_t v5 = g1; // 0x8048661
    g3 = v4 == v5;
    if (v4 == v5) {
        // 0x804868c
        function_804855d(v3, v2);
        // branch -> 0x804869e
    } else {
        // 0x804866a
        g2 = v4;
        g1 = v4;
        g3 = t == (int32_t *)-16;
        function_804855d(v3, v1);
        // branch -> 0x804869e
    }
    // 0x804869e
    if (!g3) {
        // 0x80486aa
        __stack_chk_fail();
        // branch -> 0x80486af
    }
    // 0x80486af
    return result;
}

int32_t function_80486b1(void) {
    // 0x80486b1
    g3 = false;
    // branch -> 0x80486b7
    while (true) {
        // 0x80486b7
        function_80487b0("", 1024);
        g2 = 0;
        function_80485ce(0x804a060);
        // branch -> 0x80486b7
    }
}

int main(int argc, char **argv) {
    alarm(30);
    // branch -> 0x804872b
    for (uint32_t i = 0; i < 3; i++) {
        // 0x804872b
        function_80487e4(".", 0, 0);
        sleep(1);
        // PHI copies at the loop end
        // loop 0x804872b end
    }
    // 0x804874f
    function_80487e4("Sorry, we are not able to take your call right now.\n", 0, 0);
    function_80487e4("Do you want to leave a message (y/n)? ", 0, 0);
    int8_t v1;
    function_80487b0(&v1, 4);
    g2 = v1;
    g3 = v1 == 121;
    if (v1 == 121) {
        // 0x8048784
        function_80486b1();
        // UNREACHABLE
    }
    // 0x8048797
    function_80487e4("Bye!\n", 4, 0);
    if (!g3) {
        // 0x80487a4
        __stack_chk_fail();
        // branch -> 0x80487a9
    }
    // 0x80487a9
    return 4;
}

int32_t function_80487b0(int8_t * a1, int32_t a2) {
    int32_t v1 = (int32_t)*a1; // bp+44
    int32_t v2 = a2 - 1; // 0x80487c65
    g3 = v2 == 0;
    if (v2 == 0) {
        // 0x80487dc
        a1[v1] = 0;
        return 3;
    }
    int32_t v3; // 0x80487d7
    while (true) {
        // 0x80487cb
        if (a1[v1] == 10) {
            // 0x80487dc
            a1[v1] = 0;
            return 3;
        }
        // 0x80487d7
        v3 = v1 + 1;
        int32_t v4 = v2 - 1; // 0x80487c6
        if (v4 == 0) {
            // break -> 0x80487dc
            break;
        }
        v2 = v4;
        v1 = v3;
        // continue -> 0x80487cb
    }
    // 0x80487dc
    a1[v3] = 0;
    return 3;
}

int32_t function_80487e4(int8_t * a1, int32_t a2, int32_t a3) {
    int32_t v1 = (int32_t)*a1; // bp+45
    int8_t v2 = a1[v1]; // 0x80487f55
    if (v2 == 0) {
        // 0x8048806
        return 4;
    }
    g3 = v2 == 0;
    while (a1[v1 + 1] != 0) {
        // 0x80487fa
        v1++;
        // continue -> 0x80487fa
    }
    // 0x8048806
    return 4;
}

/* --------- External Functions --------- */

// void __gmon_start__(void);
// void __stack_chk_fail(void);
// unsigned alarm(unsigned)
// struct tm *localtime(const time_t *timer)
// unsigned int sleep (unsigned int seconds)
// int sprintf (char *restrict, const char *restrict, ...)
// size_t strftime(char *restrict s, size_t maxsize, const char *restrict format, const struct tm *restrict timeptr)
// time_t time(time_t *tloc)

/* ---------- Meta-Information ---------- */

// Detected compiler: llvm (i686-pc-linux-gnu) 3.2
// Detected functions: 7 (8 in front-end)
// Decompiler release: v1.7 (Jun 30 2014)
// Decompilation date: Aug 22 2014 20:45:14
